### ISSUE TITLE
Hierarchical structure in private google drives

### ISSUE THREAD

**Issue by stevenbird** [langtech/aikuma#360]
The `/` characters in the [file storage specification](https://github.com/aikuma/aikuma/wiki/File-Storage) are intended to correspond to nested directories. Thus the following file should show up 7 levels deep, not at the root of the private google drive:

```
aikuma/v01/t/te/testrnrmf@gmail_com/items/ualwfcixlzpu/ualwfcixlzpu-testrnrmf@gmail.com-source.wav
```

**Comment by hleeldc** [comment]
@lisaslyis -- sorry, I rejected PR #377 because it changes the DataStore interface.

**Comment by stevenbird** [comment]
Adding a new file to a folder in the hierarchical private google drive will involve searching for it's parent directory (i.e. the `item_id`) and then checking that the grandparent of this directory is correct (i.e. the `user_id`).

**Comment by stevenbird** [comment]
This approach breaks down if there are multiple copies of the Aikuma folder structure in a private Google Drive. This can happen when we have multiple versions of the file structure within a single instance of the app (cf our use of a top-level version directory `v01` etc), or when a user clones some or all of the Aikuma structure manually.

**Comment by stevenbird** [comment]
Suppose the app knows the id of the `/aikuma` root directory. Then it can always be sure that we're getting the correct subdirectories, even if there are two root directories called "aikuma". Then we just need a way, within the app, for a user to specify a new root directory.

This would also support the use case where a user has two or more "projects", stored in `/aikuma1` and `/aikuma2` and switch between them.

**Comment by hleeldc** [comment]
I just learned that google drive allows per file custom properties. For example, files can be tagged with arbitrary key-value pairs. Leveraging this feature, we can modify `GoogleDriveStorage` class so that it is initialized with a unique id associated with the root aikuma folder. When a file or folder is created, two properties are attached: `aikuma_root_id` and `aikuma_file_path`. For example,

- aikuma/
  - aikuma_root_id=1c5639ec-5149-4763-a7fe-231d79cbc271
  - aikuma_file_path=/
- aikuma/v01/
  - aikuma_root_id=1c5639ec-5149-4763-a7fe-231d79cbc271
  - aikuma_file_path=/v01
- aikuma/v01/t/te/testrnrmf@gmail.com/items/ualwfcixlzpu/ualwfcixlzpu-testrnrmf@gmail.com-source.wav
  - aikuma_root_id=1c5639ec-5149-4763-a7fe-231d79cbc271 
  - aikuma_file_path=/v01/t/te/testrnrmf@gmail.com/items/ualwfcixlzpu/ualwfcixlzpu-testrnrmf@gmail.com-source.wav

With this, creating a new file can be done in 2 http requests.
  1. Find file id of containing folder: findFile(aikuma_root_id, aikuma_file_path)
  2. Add file: addFile(aikuma_root_id, aikuma_file_path, parent_id, file_content)

I think the unique root folder ID should be created by the app rather than relying on the google file ID of the root folder. It makes our cloud API simpler. Assuming that user needs to supply the root folder ID, it won't be straightforward for normal user to figure out either the google file ID or the value of the aikuma_root_id property because the google drive interface doesn't provide that information. Therefore, probably that information should be store in the root directory in a file. For instance, `aikuma_root_id.txt` can be created by the constructor of `GoogleDriveStorage`.

The `aikuma_root_id.txt` file also allows a fallback mechanism for root folder detection for directory structures created outside the app.

  1. Find a folder with specified aikuma_root_id whose aikuma_file_path is /.
  2. If 1 returns nothing, find a folder that contains aikuma_root_id.txt file whose content is the value of aikuma_root_id. If found, process all files under the folder to add aikuma_root_id and aikuma_file_path properties.

**Comment by lisaslyis** [comment]
@hleeldc Custom property is really good to differentiate folder created by Aikuma and others. I have a few questions.
1. Does Google web API interface support search with a custom property? If not, we might need more than one call to find the correct root folder. It seems like the API only support 'contain' relationship for custom properties

2. Is there any use case for an user to supply the root folder ID? I'm a little confused about the use of `aikuma_root_id.txt` except for the fallback mechanism

**Comment by hleeldc** [comment]
Sorry I didn't see your comment sooner. Regarding the `has` operator, see the example near the bottom of [this page](https://developers.google.com/drive/web/search-parameters), before the video. It's more than existence test.

@stevenbird coined the idea in his previous comment:
> Suppose the app knows the id of the /aikuma root directory. Then it can always be sure that we're getting the correct subdirectories, even if there are two root directories called "aikuma". Then we just need a way, within the app, for a user to specify a new root directory.

If you don't mind, I would like to do some work on this issue. I'm modifying the `GoogleDriveStorage` class for the file sharing feature and this seems to be related somehow -- I can't seem to separate the two features cleanly.

**Comment by stevenbird** [comment]
Note that, if a new aikuma structure is imported via Google Drive (e.g. because a user created the structure themselves) we would need to assign suitable properties to the whole structure when syncing.

**Comment by hleeldc** [comment]
Assuming that that's a one time operation that can be done by the app, it doesn't seem too bad.

**Comment by hleeldc** [comment]
If user continuously modifies the directory structure using manually or non-Aikuma application, it's not one time operation anymore. Is it the case that we want to support such scenario?

**Comment by stevenbird** [comment]
In moving forward with this issue, we will assume that aikuma directory modification only takes place on the device (e.g. via USB). We will have multiple project directories under `/aikuma`. In Google Drive, there will also be an `/aikuma` directory and Aikuma will know the id for this directory. If it is ever necessary to filter the results of querying Google Drive for a filename, we can check that they appear under this id.

**Comment by hleeldc** [comment]
PR #390 implements the what I have proposed with slight modification.
