### ISSUE TITLE
'Welcome back' for first-time user & mention in 'Getting started'

### ISSUE THREAD

**Issue by Netesten** [langtech/aikuma#570]
This may not be worth it, but just logged in for first time with a name other than anonymous, and it very nicely greeted me with 'Welcome back', should that be 'Welcome!' for the first time or does it know I have been here before, as anonymous (can it tell from info from my Pc maybe). Again, just an idea; bin if no good.

**Comment by Netesten** [comment]
in addition, 'Getting started'. Using AikumaNG' - first point refers to anonymous user - reword on line with more recent version allowing named users?

Plus, the 'Were' still needs to be changed to 'We're'

**Comment by Netesten** [comment]
Additionally, just to say, finding the tasks so far SO MUCH EASIER than the first time around. I am bouncing inbetween the Getting Started and doing the stuff (importing, respeaking) and it appears to be going well. Also the use of keys (left shift/right shift) so intuitive. Not using mouse at all. Before I was clicking frantically and I was seizing the app up I think, not sure if I was doing anything right. Ver 0.909 is a goodie.

**Comment by Lingomat** [comment]
I've been surprised by the tendency of people to use the mouse on this. I always intended it to be predominently driven by keys and had spent all my time making that work smoothly.

Thanks, I do feel we're getting somewhere now. To the point I don't mind adding a feature because there's no showstopping bug to fix :)
